---
title: "pagedown: Create Paged HTML Documents for Printing from R Markdown"
shorttitle: "Printing R Markdown with CSS"
author: "Yihui Xie and Romain Lesur"
date: '`r Sys.Date()`'
subtitle: A Less Traveled Road to PDF and Printing
output:
  pagedown::html_paged:
    toc: true
    self_contained: false
    front_cover: pagedown_hex.svg
toc-title: Contents
paged-footnotes: true
lot: true
lof: true
bibliography: index.bib
---

# Introduction

When talking about PDF and printing, we often think of tools like LaTeX and Microsoft Word. When talking about HTML and CSS, we may have never imagined their possible off-screen use such as printing to PDF.

Can we print a book with HTML and CSS? W3C published [the first working draft](https://www.w3.org/1999/06/WD-css3-page-19990623) on "Paged Media Properties for CSS(3)", which was last updated in 2013. Although the working draft has been there for nearly two decades, it is still not common to see authors write or print books with HTML and CSS. The main reason is that the W3C specs are still in the draft mode, so most web browsers have not really implemented them.

HTML and CSS still cannot beat other dominating tools like Word or LaTeX when it comes to typesetting content under the constraint of "pages". You may be disappointed by a lot of typesetting details on a paged HTML page. However, HTML and CSS can be extremely powerful and flexible in other aspects, especially when combined with the power of JavaScript. By the way, HTML works almost anywhere because it only requires a web browser.

Although most web browsers have not implemented the W3C specs for Paged Media, a JavaScript polyfill library named ["paged.js"](https://www.pagedmedia.org/paged-js/) is currently being developed to fill the gap. This library is still experimental and has many rough edges, but looks promising enough to us, so we created an R package **pagedown** [@R-pagedown] based on this JavaScript library to paginate the HTML output of R Markdown documents. You can install the package [from Github](https://github.com/rstudio/pagedown):
