name: Compiling Rmarkdown file

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install r-base r-cran-littler pandoc texlive-latex-base texlive-fonts-recommended
          sudo su - -c "R -e \"install.packages('rmarkdown', repos='http://cran.rstudio.com/')\""
      - name: Compile document
        run: Rscript -e "rmarkdown::render('index.rmd', quiet=TRUE)"

      - name: Upload report result for compile
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: index.pdf
